APPLICATION_WIDTH: int = 800            # 800
APPLICATION_HEIGHT: int = 600           # 600
APPLICATION_NAME: str = "Image Editor"

ACTION_SAVE_TITTLE: str = "Save"
ACTION_SAVE_SHORTCUT: str = "Ctrl+S"
ACTION_SAVE_STATUS_TIP: str = "Save file"
ACTION_SAVE_ICON_DIR: str = None

ACTION_EXIT_TITTLE: str = "Exit"
ACTION_EXIT_SHORTCUT: str = "Ctrl+Shift+Q"
ACTION_EXIT_STATUS_TIP: str = "Exit application"
ACTION_EXIT_ICON_DIR: str = None

ACTION_SAVE_AS_TITTLE: str = "Save as"
ACTION_SAVE_AS_SHORTCUT: str = "Ctrl+Shift+S"
ACTION_SAVE_AS_STATUS_TIP: str = "Save with other name"
ACTION_SAVE_AS_ICON_DIR: str = None

ACTION_OPEN_IMAGE_TITTLE: str = "Open"
ACTION_OPEN_IMAGE_SHORTCUT: str = "Ctrl+O"
ACTION_OPEN_IMAGE_STATUS_TIP: str = "Open new image"
ACTION_OPEN_IMAGE_ICON_DIR: str = None

ACTION_CLOSE_IMAGE_TITTLE: str = "Close"
ACTION_CLOSE_IMAGE_SHORTCUT: str = "Ctrl+Q"
ACTION_CLOSE_IMAGE_STATUS_TIP: str = "Close current image"
ACTION_CLOSE_IMAGE_ICON_DIR: str = None

ACTION_SETTINGS_TOOLBAR_TITTLE: str = "Toolbar settings"
ACTION_SETTINGS_TOOLBAR_SHORTCUT: str = "Ctrl+T"
ACTION_SETTINGS_TOOLBAR_STATUS_TIP: str = "Setting toolbar items"
ACTION_SETTINGS_TOOLBAR_ICON_DIR: str = None

ACTION_CLEAR_TOOLBAR_TITTLE: str = "Clear toolbar"
ACTION_CLEAR_TOOLBAR_SHORTCUT: str = "Ctrl+Shift+T"
ACTION_CLEAR_TOOLBAR_STATUS_TIP: str = "Remove all items from toolbar"
ACTION_CLEAR_TOOLBAR_ICON_DIR: str = None

ACTION_ROTATE_LEFT_TITTLE: str = "Rotate to left"
ACTION_ROTATE_LEFT_SHORTCUT: str = None
ACTION_ROTATE_LEFT_STATUS_TIP: str = "Rotate at 90 degrees anticlockwise"
ACTION_ROTATE_LEFT_ICON_DIR: str = None

ACTION_ROTATE_RIGHT_TITTLE: str = "Rotate to right"
ACTION_ROTATE_RIGHT_SHORTCUT: str = None
ACTION_ROTATE_RIGHT_STATUS_TIP: str = "Rotate at 90 degrees clockwise"
ACTION_ROTATE_RIGHT_ICON_DIR: str = None

ACTION_VERTICAL_MIRRORING_TITTLE: str = "Mirroring vertical"
ACTION_VERTICAL_MIRRORING_SHORTCUT: str = None
ACTION_VERTICAL_MIRRORING_STATUS_TIP: str = "Mirroring vertical"
ACTION_VERTICAL_MIRRORING_ICON_DIR: str = None

ACTION_HORIZONTAL_MIRRORING_TITTLE: str = "Mirroring horizontal"
ACTION_HORIZONTAL_MIRRORING_SHORTCUT: str = None
ACTION_HORIZONTAL_MIRRORING_STATUS_TIP: str = "Mirroring horizontal"
ACTION_HORIZONTAL_MIRRORING_ICON_DIR: str = None

ACTION_COLOR_INVERSE_TITTLE: str = "Color inverse"
ACTION_COLOR_INVERSE_SHORTCUT: str = None
ACTION_COLOR_INVERSE_STATUS_TIP: str = "Color inverse"
ACTION_COLOR_INVERSE_ICON_DIR: str = None

ACTION_CHANGE_COLOR_VALUE_PLUS_TITTLE: str = "Color +"
ACTION_CHANGE_COLOR_VALUE_PLUS_SHORTCUT: str = None
ACTION_CHANGE_COLOR_VALUE_PLUS_STATUS_TIP: str = "Change color value"
ACTION_CHANGE_COLOR_VALUE_PLUS_ICON_DIR: str = None

ACTION_CHANGE_COLOR_VALUE_MINUS_TITTLE: str = "Color -"
ACTION_CHANGE_COLOR_VALUE_MINUS_SHORTCUT: str = None
ACTION_CHANGE_COLOR_VALUE_MINUS_STATUS_TIP: str = "Change color value"
ACTION_CHANGE_COLOR_VALUE_MINUS_ICON_DIR: str = None

ACTION_CONVERT_TO_GRAY_SCALE_TITTLE: str = "Gray scale"
ACTION_CONVERT_TO_GRAY_SCALE_SHORTCUT: str = None
ACTION_CONVERT_TO_GRAY_SCALE_STATUS_TIP: str = "Convert to gray scale"
ACTION_CONVERT_TO_GRAY_SCALE_ICON_DIR: str = None

ACTION_BORDER_FOCUS_TITTLE: str = "Border focus"
ACTION_BORDER_FOCUS_SHORTCUT: str = None
ACTION_BORDER_FOCUS_STATUS_TIP: str = "Border focus"
ACTION_BORDER_FOCUS_ICON_DIR: str = None

ACTION_ORIGINAL_IMAGE_TITTLE: str = "Original image"
ACTION_ORIGINAL_IMAGE_SHORTCUT: str = "Ctrl+I"
ACTION_ORIGINAL_IMAGE_STATUS_TIP: str = "Rollback to original image"
ACTION_ORIGINAL_IMAGE_ICON_DIR: str = None
